package com.serkyo.simplycompat.config;

import com.serkyo.simplycompat.SimplyCompat;

import java.util.Arrays;

public class SCBakedConfigs {
    public static int COPPER_DAMAGE_MODIFIER;
    public static int SILVER_DAMAGE_MODIFIER;
    public static int SILVER_BONUS_DAMAGE;
    public static int MYRMEX_DAMAGE_MODIFIER;
    public static int MYRMEX_BONUS_DAMAGE;
    public static int MYRMEX_STINGER_POISON_CHANCE;
    public static int MYRMEX_STINGER_POISON_DURATION;
    public static int MYRMEX_STINGER_POISON_LEVEL;
    public static int DRAGONBONE_DAMAGE_MODIFIER;
    public static int INFUSED_DRAGONBONE_DAMAGE_MODIFIER;
    public static int INFUSED_DRAGONBONE_BONUS_DAMAGE;
    public static int INFUSED_DRAGONBONE_KNOCKBACK;
    public static int FIRE_INFUSED_DRAGONBONE_BURN_TIME;
    public static int ICE_INFUSED_DRAGONBONE_FREEZE_TIME;
    public static int DRAGONSTEEL_DAMAGE_MODIFIER;
    public static boolean DRAGONSTEEL_REWORK;
    public static int DRACONIC_RESONANCE_DURATION;
    public static int DRACONIC_RESONANCE_MAX_LEVEL;
    public static float DRACONIC_RESONANCE_ATTACK_BONUS;
    public static String DRACONIC_RESONANCE_ATTACK_OPERATION;
    public static float DRACONIC_RESONANCE_ARMOR_BONUS;
    public static String DRACONIC_RESONANCE_ARMOR_OPERATION;
    public static float DRACONIC_RESONANCE_ARMOR_TOUGHNESS_BONUS;
    public static String DRACONIC_RESONANCE_ARMOR_TOUGHNESS_OPERATION;
    public static float DRACONIC_RESONANCE_SPEED_BONUS;
    public static String DRACONIC_RESONANCE_SPEED_OPERATION;
    public static float DRACONIC_RESONANCE_ATTACK_SPEED_BONUS;
    public static String DRACONIC_RESONANCE_ATTACK_SPEED_OPERATION;
    public static int DRAGONSTEEL_KNOCKBACK;
    public static int FIRE_DRAGONSTEEL_BURN_TIME;
    public static int ICE_DRAGONSTEEL_FREEZE_TIME;


    public static void bakeCommon() {
        SimplyCompat.LOGGER.debug("Loading common configuration from file ...");
        try {
            COPPER_DAMAGE_MODIFIER = SCCommonConfigs.COPPER_DAMAGE_MODIFIER.get();
            SILVER_DAMAGE_MODIFIER = SCCommonConfigs.SILVER_DAMAGE_MODIFIER.get();
            SILVER_BONUS_DAMAGE = SCCommonConfigs.SILVER_BONUS_DAMAGE.get();
            MYRMEX_DAMAGE_MODIFIER = SCCommonConfigs.MYRMEX_DAMAGE_MODIFIER.get();
            MYRMEX_BONUS_DAMAGE = SCCommonConfigs.MYRMEX_BONUS_DAMAGE.get();
            MYRMEX_STINGER_POISON_CHANCE = SCCommonConfigs.MYRMEX_STINGER_POISON_CHANCE.get();
            MYRMEX_STINGER_POISON_DURATION = SCCommonConfigs.MYRMEX_STINGER_POISON_DURATION.get();
            MYRMEX_STINGER_POISON_LEVEL = SCCommonConfigs.MYRMEX_STINGER_POISON_LEVEL.get();
            DRAGONBONE_DAMAGE_MODIFIER = SCCommonConfigs.DRAGONBONE_DAMAGE_MODIFIER.get();
            INFUSED_DRAGONBONE_DAMAGE_MODIFIER = SCCommonConfigs.INFUSED_DRAGONBONE_DAMAGE_MODIFIER.get();
            INFUSED_DRAGONBONE_BONUS_DAMAGE = SCCommonConfigs.INFUSED_DRAGONBONE_BONUS_DAMAGE.get();
            INFUSED_DRAGONBONE_KNOCKBACK = SCCommonConfigs.INFUSED_DRAGONBONE_KNOCKBACK.get();
            FIRE_INFUSED_DRAGONBONE_BURN_TIME = SCCommonConfigs.FIRE_INFUSED_DRAGONBONE_BURN_TIME.get();
            ICE_INFUSED_DRAGONBONE_FREEZE_TIME = SCCommonConfigs.ICE_INFUSED_DRAGONBONE_FREEZE_TIME.get();
            DRAGONSTEEL_DAMAGE_MODIFIER = SCCommonConfigs.DRAGONSTEEL_DAMAGE_MODIFIER.get();
            DRAGONSTEEL_REWORK = SCCommonConfigs.DRAGONSTEEL_REWORK.get();
            DRACONIC_RESONANCE_DURATION = SCCommonConfigs.DRACONIC_RESONANCE_DURATION.get();
            DRACONIC_RESONANCE_MAX_LEVEL = SCCommonConfigs.DRACONIC_RESONANCE_MAX_LEVEL.get();
            DRACONIC_RESONANCE_ATTACK_BONUS = SCCommonConfigs.DRACONIC_RESONANCE_ATTACK_BONUS.get();
            DRACONIC_RESONANCE_ATTACK_OPERATION = SCCommonConfigs.DRACONIC_RESONANCE_ATTACK_OPERATION.get();
            DRACONIC_RESONANCE_ARMOR_BONUS = SCCommonConfigs.DRACONIC_RESONANCE_ARMOR_BONUS.get();
            DRACONIC_RESONANCE_ARMOR_OPERATION = SCCommonConfigs.DRACONIC_RESONANCE_ARMOR_OPERATION.get();
            DRACONIC_RESONANCE_ARMOR_TOUGHNESS_BONUS = SCCommonConfigs.DRACONIC_RESONANCE_ARMOR_TOUGHNESS_BONUS.get();
            DRACONIC_RESONANCE_ARMOR_TOUGHNESS_OPERATION = SCCommonConfigs.DRACONIC_RESONANCE_ARMOR_TOUGHNESS_OPERATION.get();
            DRACONIC_RESONANCE_SPEED_BONUS = SCCommonConfigs.DRACONIC_RESONANCE_SPEED_BONUS.get();
            DRACONIC_RESONANCE_SPEED_OPERATION = SCCommonConfigs.DRACONIC_RESONANCE_SPEED_OPERATION.get();
            DRACONIC_RESONANCE_ATTACK_SPEED_BONUS = SCCommonConfigs.DRACONIC_RESONANCE_ATTACK_SPEED_BONUS.get();
            DRACONIC_RESONANCE_ATTACK_SPEED_OPERATION = SCCommonConfigs.DRACONIC_RESONANCE_ATTACK_SPEED_OPERATION.get();
            DRAGONSTEEL_KNOCKBACK = SCCommonConfigs.DRAGONSTEEL_KNOCKBACK.get();
            FIRE_DRAGONSTEEL_BURN_TIME = SCCommonConfigs.FIRE_DRAGONSTEEL_BURN_TIME.get();
            ICE_DRAGONSTEEL_FREEZE_TIME = SCCommonConfigs.ICE_DRAGONSTEEL_FREEZE_TIME.get();

        }
        catch (Exception e) {
            SimplyCompat.LOGGER.error("An exception has occured while trying to load the common config for Simply Compat");
            SimplyCompat.LOGGER.error(Arrays.toString(e.getStackTrace()));
        }
    }
}
